import Apple from "../resources/apples-prd.jpg";
import { Products } from "../types/shop.types";

export const sampleProducts: Array<Products> = [
  {
    id: 1,
    name: "Fresh Apples",
    price: 150,
    image: Apple,
    type: "pome",
    orderCount: 3,
    reviewCount: 3,
    description: "Sample Description of Apples",
  },
  {
    id: 2,
    name: "Ripe Bananas",
    price: 60,
    image: Apple,
    type: "stone",
    orderCount: 2,
    reviewCount: 2,
    description: "Sample Description of Bananas",
  },
  {
    id: 3,
    name: "Juicy Oranges",
    price: 120,
    image: Apple,
    type: "pome",
    orderCount: 3,
    reviewCount: 3,
    description: "Sample Description of Oranges",
  },
  {
    id: 4,
    name: "Sweet Strawberries",
    price: 200,
    image: Apple,
    type: "pome",
    orderCount: 4,
    reviewCount: 4,
    description: "Sample Description of Strawberries",
  },
  {
    id: 5,
    name: "Grapes",
    price: 180,
    image: Apple,
    type: "stone",
    orderCount: 10,
    reviewCount: 10,
    description: "Sample Description of Grapes",
  },
  {
    id: 6,
    name: "Mangoes",
    price: 250,
    image: Apple,
    type: "stone",
    orderCount: 0,
    reviewCount: 0,
    description: "Sample Description of Mangoes",
  },
  {
    id: 7,
    name: "Peaches",
    price: 220,
    image: Apple,
    type: "tropical",
    orderCount: 2,
    reviewCount: 2,
    description: "Sample Description of Peaches",
  },
  {
    id: 8,
    name: "Limes",
    price: 70,
    image: Apple,
    type: "pome",
    orderCount: 7,
    reviewCount: 7,
    description: "Sample Description of Limes",
  },
  {
    id: 9,
    name: "Pineapples",
    price: 300,
    image: Apple,
    type: "citrus",
    orderCount: 3,
    reviewCount: 3,
    description: "Sample Description of Pineapples",
  },
  {
    id: 10,
    name: "Watermelons",
    price: 350,
    image: Apple,
    type: "pome",
    orderCount: 2,
    reviewCount: 2,
    description: "Sample Description of Watermelons",
  },
  {
    id: 11,
    name: "Cherries",
    price: 400,
    image: Apple,
    type: "berries",
    orderCount: 1,
    reviewCount: 1,
    description: "Sample Description of Cherries",
  },
  {
    id: 12,
    name: "Papayas",
    price: 130,
    image: Apple,
    type: "others",
    orderCount: 0,
    reviewCount: 0,
    description: "Sample Description of Papayas",
  },
];
